### ISSUE TITLE
[Bug] Pause while rendering dialogue

### ISSUE THREAD

**Issue by Klyukich** [lokinmodar/Echoglossian#45]
Good afternoon, tell me please, maybe I did not find the information, but as I see the last update was in April. Am I right in thinking that mod maintenance is suspended? It's just that the topic with a frieze for a second when the translation is in progress was a year ago and the problem has persisted.

**Comment by lokinmodar** [comment]
> Good afternoon, tell me please, maybe I did not find the information, but as I see the last update was in April. Am I right in thinking that mod maintenance is suspended? It's just that the topic with a frieze for a second when the translation is in progress was a year ago and the problem has persisted.

Hello!

The plugin's code wasn't updated after april for the current release because of real life issues on my side but the plugin itself is working fine in the way it is today apart from the micro-stutters. I know they are annoying but i'm working slowly so i can solve it and many other issues and improvements for a new major version update. No ETA yet but i'm watching the comments on the goatplace discord and here. Please wait a little bit more.

For the moment i recommend using the translation overlay instead of the native UI dialogue text box replacement. This option does not cause stuttering and also supports more languages with different script types not supported by the game's native font.

**Comment by Klyukich** [comment]
Thank you I will be waiting
