### ISSUE TITLE
Awaiting translation...

### ISSUE THREAD

**Issue by Kruis** [lokinmodar/Echoglossian#55]
Hi,
Is it possible to remove the "Awaiting translation..." (or similar) message that appears just before the text is translated? It's rather annoying as well as useless, given that the translation takes place in less than a second.
You just have time to see something black appear, illegible in 99% of cases because it is immediately replaced by the translated text... but it is visually annoying.
Or at least you could make it appear with a latency of 2 seconds if the text has not been translated in the meantime.
This also applies to the translation of the character's name!

Thank you especially for the excellent work!

**Comment by arxdeus** [comment]
+1

**Comment by lokinmodar** [comment]
Current work on the fix for the stuttering will probably fix this and there won't be need for the message to be displayed. I'll take a look after the fix implementation of the fix i'm working on and decide if there is still a need for the message :) 

This is the issue i'm working right now: https://github.com/lokinmodar/Echoglossian/issues/72
